/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        coinbase: {
          primary: 'var(--color-accent)',
          'primary-active': 'var(--color-accent-hover)',
          'primary-disabled': '#A8B8CC',
          ink: 'var(--color-ink)',
          body: 'var(--color-text)',
          'body-strong': 'var(--color-ink)',
          muted: 'var(--color-text-light)',
          'muted-soft': 'var(--color-muted-soft)',
          hairline: 'var(--color-border)',
          'hairline-soft': 'var(--color-hover)',
          canvas: 'var(--color-bg)',
          'surface-soft': 'var(--color-bg-alt)',
          'surface-card': 'var(--color-bg)',
          'surface-strong': 'var(--color-surface-strong)',
          hover: 'var(--color-hover)',
          'surface-dark': '#0A0B0D',
          'surface-dark-elevated': '#16181C',
          'on-primary': 'var(--color-on-primary)',
          'on-dark': '#FFFFFF',
          'on-dark-soft': '#A8ACB3',
          'semantic-up': 'var(--color-semantic-up)',
          'semantic-down': 'var(--color-semantic-down)',
          'accent-yellow': '#F4B000',
          'primary-btn': 'var(--color-primary-btn)',
          'primary-btn-hover': 'var(--color-primary-btn-hover)',
        },
      },
      fontFamily: {
        display: ["'PingFang SC'", "'Microsoft YaHei'", "'微软雅黑'", '-apple-system', 'BlinkMacSystemFont', "'Segoe UI'", 'Roboto', 'Helvetica', 'Arial', 'sans-serif'],
        sans: ["'PingFang SC'", "'Microsoft YaHei'", "'微软雅黑'", '-apple-system', 'BlinkMacSystemFont', "'Segoe UI'", 'Roboto', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ["'PingFang SC'", "'JetBrains Mono'", 'monospace'],
      },
      borderRadius: {
        'coinbase-xs': '4px',
        'coinbase-sm': '8px',
        'coinbase-md': '12px',
        'coinbase-lg': '16px',
        'coinbase-xl': '24px',
        'coinbase-pill': '100px',
        'coinbase-full': '9999px',
      },
      spacing: {
        'coinbase-xxs': '4px',
        'coinbase-xs': '8px',
        'coinbase-sm': '12px',
        'coinbase-base': '16px',
        'coinbase-md': '20px',
        'coinbase-lg': '24px',
        'coinbase-xl': '32px',
        'coinbase-xxl': '48px',
        'coinbase-section': '96px',
      },
      boxShadow: {
        'coinbase-soft': '0 4px 12px var(--color-shadow)',
        'coinbase-hover': '0 4px 12px var(--color-shadow)',
      },
      fontSize: {
        'coinbase-button': ['16px', { lineHeight: '1.15', fontWeight: '600' }],
        'coinbase-nav': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'coinbase-caption': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'coinbase-caption-strong': ['12px', { lineHeight: '1.5', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
